### ISSUE TITLE
Won't report wins for me

### ISSUE THREAD

**Issue by adamloving** [gorried/pingpong#4]
To repro
1. Click "add game"
2. Leave "Adam Loving" selected in the top drop down
3. Select anybody from the second drop down
4. Click "add"

Expected:
A win for Adam is reported!

Actual:
Nothing happens

Work aroudn: 
Choose another name first, then switch back to Adam.

I was going to fix this myself, but balked at installing flask. Setting the value attribute of the option elements might fix this (or the selected attribute of the first element).

**Comment by gorried** [comment]
Closed by 1a3b6ef
